### PR TITLE
blog styling

### PR DESCRIPTION
**Pull request by trotod**
This PR ~~introduces a simple blog for blogging. Any thoughts?~~ now fixes up the styling of the private blog.

By the way anything in _drafts is just for testing, it won't be included on build.

### CODE REVIEW

**Comment by m3rcuriel** [comment]
We're not going to have a blog on the site.

**Comment by akhil99** [comment]
Recently, we discussed having a blog, and came up with a certain list of criteria. This needs to be discussed further before implementation

**Comment by trotod** [comment]
I was on vacation for a while, so sure, this can wait.

**Comment by m3rcuriel** [comment]
We'll probably end up doing this through the facebook api later or something. No one wants a public blog.

**Comment by trotod** [comment]
Updated the PR with changes to blog styling.

**Comment by m3rcuriel** [comment]
How does this interact with the private blog, in terms of layout, etc

**Comment by trotod** [comment]
it applies some extra styles to the private blog...

layout changes: change heading colors from purple to black (almost makes it look like its a visited link)

nothing content wise changes

before:
http://a.pomf.se/gtnbyu.png

after:
http://a.pomf.se/xidcbh.png

**Comment by trotod** [comment]
shovik said I could merge it.

**Comment by m3rcuriel** [comment]
Idk why but there are no spaces around the date

**Comment by trotod** [comment]
It's probably a problem with the HTML minification; it removes spaces around most elements.

See #24 for a hackish fix.

**Pull request merged**
