### PR TITLE
Fixed navigation in about page, now dynamically refreshes content

### PR DESCRIPTION
**Pull request by akhil99**

### CODE REVIEW

**Comment by akhil99** [comment]
@m3rcuriel can you merge this?

**Comment by trotod** [comment]
you may need to rebase it....

**Comment by m3rcuriel** [comment]
Realllyyyy.... /s

**Comment by m3rcuriel** [comment]
line 1   col 22  Strings must use singlequote.
      line 10  col 16  Strings must use singlequote.
      line 10  col 13  Expected '===' and instead saw '=='.
      line 12  col 31  Strings must use singlequote.
      line 12  col 19  Expected '===' and instead saw '=='.
      line 16  col 17  'setPage' was used before it was defined.
      line 17  col 22  Strings must use singlequote.

**Comment by m3rcuriel** [comment]
Okay so it compiled (?)

Team Members needs to be less forceful. It's odd to have this nice dynamic content and then *boom*

**Comment by trotod** [comment]
use `===` (strict equality), not `==` (type equality? i forget)

Javascript has weird quirks.

**Pull request merged**
